#!/bin/bash
#==========================#WORKER SCRIPT#==========================#

# Function to extract value from JSON
get_json_value() {
    key=$1
    file=$2
    grep -o "\"$key\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" "$file" | sed "s/\"$key\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\"/\1/"
}


### move into directory of peptide ###
cd "$1"

### LOAD Variables ###
JSON_FILE="../../../../../X.Scripts/binder_md_sim/data_gromacs.json"
PEPTIDE=$(ls *.pdb | head -n 1)
WATER_MODEL=$(get_json_value "water_model" "$JSON_FILE")
FORCE_FIELD=$(get_json_value "force_field" "$JSON_FILE")
DIMENSION_BOX=$(get_json_value "dimension_box" "$JSON_FILE")
FORM_BOX=$(get_json_value "form_box" "$JSON_FILE")


### Create necessary directories ###
mkdir -p 1.topology  2.solvation 3.ions 4.minimization 5.equilibriation_first 5.equilibriation_second 6.md_sim 7.analysis


### Copy running scripts into correct folders ###
cp ../../../../../X.Scripts/binder_md_sim/ions.mdp 3.ions/
cp ../../../../../X.Scripts/binder_md_sim/minim.mdp 4.minimization/
cp ../../../../../X.Scripts/binder_md_sim/npt_first.mdp 5.equilibriation_first/
cp ../../../../../X.Scripts/binder_md_sim/npt_second.mdp 5.equilibriation_second/
cp ../../../../../X.Scripts/binder_md_sim/md.mdp 6.md_sim/


### Load Force Field ###
export GMXLIB="/home/kunzj/internship_uva_compchem/X.Scripts/binder_md_sim/" # needs to be absolute and not relative !!!

# Load name of ligand
awk '$12 !~ /^H/ {print $0}' ${PEPTIDE} > complex_noH.pdb # ~ needed to remove hydrogens and add them later as peptides generated by bindcraft can have wrong annotation 

# generate pdb file containing only protein and peptide

awk '/^ATOM/ || /^HETATM/ { if(substr($0,22,1)=="B") print $0 }' complex_noH.pdb > onlyPeptide.pdb

awk '/^ATOM/ || /^HETATM/ { if(substr($0,22,1)=="A") print $0 }' complex_noH.pdb > onlyProtein.pdb



# Topology
 
# deal with MET at start or end 
detect_met_positions() {
    local pdbfile="$1"

    # Initialize globals
    declare -g MET_output
    declare -g chains_list
    MET_output=()
    chains_list=()

    # Extract all unique chains in order of appearance
    mapfile -t chains_list < <(awk 'substr($0,22,1)!=" " && !seen[substr($0,22,1)]++ {print substr($0,22,1)}' "$pdbfile")

    # Initialize MET_output with 0 for each start/end position
    for ((i=0; i<${#chains_list[@]}*2; i++)); do
        MET_output[i]=0
    done

    local code=0

    # Loop over each chain
    for chain in "${chains_list[@]}"; do
        # Get first residue number
        first_res=$(awk -v c="$chain" 'substr($0,22,1)==c {print substr($0,23,4)+0; exit}' "$pdbfile")
        # Get last residue number
        last_res=$(awk -v c="$chain" 'substr($0,22,1)==c {res=substr($0,23,4)+0} END{print res}' "$pdbfile")

        # Get residue names at first and last residue
        start_resname=$(awk -v c="$chain" -v r="$first_res" 'substr($0,22,1)==c && (substr($0,23,4)+0)==r {resname=substr($0,18,3); gsub(/ /,"",resname); print resname; exit}' "$pdbfile")
        end_resname=$(awk -v c="$chain" -v r="$last_res" 'substr($0,22,1)==c && (substr($0,23,4)+0)==r {resname=substr($0,18,3); gsub(/ /,"",resname); print resname; exit}' "$pdbfile")

        # Update MET_output array
        [ "$start_resname" == "MET" ] && MET_output[code]=1
        ((code++))
        [ "$end_resname" == "MET" ] && MET_output[code]=1
        ((code++))
    done
}

cd ./1.topology

# complex

detect_met_positions "../complex_noH.pdb"

echo "${MET_output[@]}"
echo "${MET_output[@]}" | gmx_mpi pdb2gmx -f ../complex_noH.pdb -o ./complex.gro -water ${WATER_MODEL} -ff ${FORCE_FIELD} -missing -ter 


# peptide
mkdir ./peptide_only
cd ./peptide_only



detect_met_positions "../../onlyPeptide.pdb"


echo "${MET_output[@]}"
echo "${MET_output[@]}" | gmx_mpi pdb2gmx -f ../../onlyPeptide.pdb -o ./only_peptide.gro -water ${WATER_MODEL} -ff ${FORCE_FIELD} -missing -ter

cd ../

# index creation - protein

gmx_mpi make_ndx -f complex.gro -o ./index_protein.ndx <<EOF
ri 1-160
ri 161-200 & ! r SOL & ! r NA & ! r CL
ri 1-200 & ! r SOL & ! r NA & ! r CL
10 & a CA
11 & a CA
name 10 onlyProtein 
name 11 onlyPeptide 
name 12 Prot+Pept
name 13 CAonlyProtein
name 14 CAonlyPeptide
q
EOF

# index creation - peptide

### not needed as everything already there ###


# restraint creation

echo 13 | gmx_mpi genrestr -f complex.gro -n  ./index_protein.ndx -o posre_chainA_strong.itp -fc 1000 # restrains CA protein - 1000 KJ/mol
echo 13 | gmx_mpi genrestr -f complex.gro -n  ./index_protein.ndx -o posre_chainA_weak.itp -fc 100 # restrains CA protein - 100 KJ/mol

echo 3 | gmx_mpi genrestr -f ./peptide_only/only_peptide.gro  -o posre_chainB_strong.itp -fc 1000 # restrains CA peptide - 1000 KJ/mol
echo 3 | gmx_mpi genrestr -f ./peptide_only/only_peptide.gro  -o posre_chainB_weak.itp -fc 100 # restrains CA peptide - 100 KJ/mol



# adding restrain to topol_*chains* file

echo '; ---- position restraints for Chain A ----
#ifdef POSRES_STRONG
#include "posre_chainA_strong.itp"
#endif
#ifdef POSRES_WEAK
#include "posre_chainA_weak.itp"
#endif' >> topol_Protein_chain_A.itp

echo '; ---- position restraints for Chain B ----
#ifdef POSRES_STRONG
#include "posre_chainB_strong.itp"
#endif
#ifdef POSRES_WEAK
#include "posre_chainB_weak.itp"
#endif' >> topol_Protein_chain_B.itp



### Solvation ###
cd ../2.solvation

gmx_mpi editconf -f ../1.topology/complex.gro -o ./complex_NewBox.gro -c -d ${DIMENSION_BOX} -bt ${FORM_BOX}
gmx_mpi solvate -cp ./complex_NewBox.gro -cs -o ./complex_solvated.gro -p ../1.topology/topol.top


### Ions ###
cd ../3.ions 

gmx_mpi grompp -f ions.mdp -c ../2.solvation/complex_solvated.gro -p ../1.topology/topol.top -o ions.tpr -maxwarn 1
echo 13 | gmx_mpi genion -s ions.tpr -o complex_solv_ions.gro -p ../1.topology/topol.top -pname NA -nname CL -conc 0.150 -neutral


### minimization ###
cd ../4.minimization

gmx_mpi grompp -f minim.mdp -c ../3.ions/complex_solv_ions.gro -p ../1.topology/topol.top -o em.tpr
gmx_mpi mdrun -deffnm em


### equilibration two steps###
cd ../5.equilibriation_first

gmx_mpi grompp -f npt_first.mdp -c ../4.minimization/em.gro -r ../4.minimization/em.gro -p ../1.topology/topol.top -o npt_first.tpr -maxwarn 1
gmx_mpi mdrun -deffnm npt_first

cd ../5.equilibriation_second

gmx_mpi grompp -f npt_second.mdp -c ../5.equilibriation_first/npt_first.gro -r ../5.equilibriation_first/npt_first.gro -t ../5.equilibriation_first/npt_first.cpt -p ../1.topology/topol.top -o npt.tpr -maxwarn 1
gmx_mpi mdrun -deffnm npt


### md-sim ###
cd ../6.md_sim

gmx_mpi grompp -f md.mdp -c ../5.equilibriation_second/npt.gro -p ../1.topology/topol.top -o md_0_1.tpr
gmx_mpi mdrun -deffnm md_0_1 -nb gpu >& ./md.out
