#!/bin/bash
#==========================#WORKER SCRIPT#==========================#

# Function to extract value from JSON
get_json_value() {
    key=$1
    file=$2
    grep -o "\"$key\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" "$file" | sed "s/\"$key\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\"/\1/"
}


### move into directory of peptide ###
cd "$1"

### LOAD Variables ###
JSON_FILE="../../../../../X.Scripts/umbrella_sampling/data_gromacs.json"
PEPTIDE=$(ls *.pdb | head -n 1)
WATER_MODEL=$(get_json_value "water_model" "$JSON_FILE")
FORCE_FIELD=$(get_json_value "force_field" "$JSON_FILE")
DIMENSION_BOX=$(get_json_value "dimension_box" "$JSON_FILE")
FORM_BOX=$(get_json_value "form_box" "$JSON_FILE")


### Create necessary directories ###
mkdir -p 1.topology  2.solvation 3.ions 4.minimization 5.equilibriation_first  5.equilibriation_second 6.pull 7.umbrella 8.analysis


### Copy running scripts into correct folders ###
cp ../../../../../X.Scripts/umbrella_sampling/ions.mdp 3.ions/
cp ../../../../X.Scripts/umbrella_sampling/minim.mdp 4.minimization/
cp ../../../../X.Scripts/umbrella_sampling/npt_first.mdp 5.equilibriation_first/
cp ../../../../X.Scripts/umbrella_sampling/npt_second.mdp 5.equilibriation_second/
cp ../../../../X.Scripts/umbrella_sampling/pull.mdp 6.pull/


cp ../../../../X.Scripts/umbrella_sampling/run_frame.sh 7.umbrella/

cp ../../../../X.Scripts/umbrella_sampling/umbrella.slurm 7.umbrella/

cp ../../../../X.Scripts/umbrella_sampling/md_frame.mdp 7.umbrella/
cp ../../../../X.Scripts/umbrella_sampling/npt_frame.mdp 7.umbrella/



### Load Force Field ###
export GMXLIB="/home/kunzj/whole_pipeline/X.Scripts/umbrella_sampling/" # needs to be absolute and not relative !!!

# Load name of ligand
awk '$12 !~ /^H/ {print $0}' ${PEPTIDE} > complex_noH.pdb # ~ needed to remove hydrogens and add them later as peptides generated by bindcraft can have wrong annotation 

# generate pdb file containing only protein and peptide

awk '/^ATOM/ || /^HETATM/ { if(substr($0,22,1)=="B") print $0 }' complex_noH.pdb > onlyPeptide.pdb

awk '/^ATOM/ || /^HETATM/ { if(substr($0,22,1)=="A") print $0 }' complex_noH.pdb > onlyProtein.pdb



# Topology
cd ./1.topology

# complex
echo 0 0 1 1 | gmx_mpi pdb2gmx -f ../complex_noH.pdb -o ./complex.gro -water ${WATER_MODEL} -ff ${FORCE_FIELD} -missing -ter 


# peptide
mkdir ./peptide_only
cd ./peptide_only

echo 1 1 | gmx_mpi pdb2gmx -f ../../onlyPeptide.pdb -o ./only_peptide.gro -water ${WATER_MODEL} -ff ${FORCE_FIELD} -missing -ter

cd ../

# index creation - protein
gmx_mpi make_ndx -f complex.gro -o ./index_protein.ndx <<EOF
ri 1-160
ri 161-200
ri 1-200
ri 1-160 & a CA
ri 161-200 & a CA
name 10 onlyProtein 
name 11 onlyPeptide 
name 12 Prot+Pept
name 13 CAonlyProtein
name 14 CAonlyPeptide
q
EOF

# index creation - peptide

### not needed as everything already there ###


# restraint creation

echo 13 | gmx_mpi genrestr -f complex.gro -n  ./index_protein.ndx -o posre_chainA_strong.itp -fc 1000 # restrains CA protein - 1000 KJ/mol
echo 13 | gmx_mpi genrestr -f complex.gro -n  ./index_protein.ndx -o posre_chainA_weak.itp -fc 100 # restrains CA protein - 100 KJ/mol

echo 3 | gmx_mpi genrestr -f ./peptide_only/only_peptide.gro  -o posre_chainB_strong.itp -fc 1000 # restrains CA peptide - 1000 KJ/mol
echo 3 | gmx_mpi genrestr -f ./peptide_only/only_peptide.gro  -o posre_chainB_weak.itp -fc 100 # restrains CA peptide - 100 KJ/mol



# adding restrain to topol_*chains* file

echo '; ---- position restraints for Chain A ----
#ifdef POSRES_STRONG
#include "posre_chainA_strong.itp"
#endif
#ifdef POSRES_STRONG_only_A
#include "posre_chainA_strong.itp"
#endif
#ifdef POSRES_WEAK
#include "posre_chainA_weak.itp"
#endif' >> topol_Protein_chain_A.itp

echo '; ---- position restraints for Chain B ----
#ifdef POSRES_STRONG
#include "posre_chainB_strong.itp"
#endif
#ifdef POSRES_WEAK
#include "posre_chainB_weak.itp"
#endif' >> topol_Protein_chain_B.itp



### Solvation and Box dimension###
cd ../2.solvation

gmx_mpi editconf -f ../1.topology/complex.gro -o ./complex_NewBox.gro -center 3.773 3.773 3.773 -box 7.547 7.547 18.000 -rotate -60 10 0
gmx_mpi solvate -cp ./complex_NewBox.gro -cs -o ./complex_solvated.gro -p ../1.topology/topol.top


### Ions ###
cd ../3.ions 

gmx_mpi grompp -f ions.mdp -c ../2.solvation/complex_solvated.gro -p ../1.topology/topol.top -o ions.tpr -maxwarn 1 
echo 13 | gmx_mpi genion -s ions.tpr -o complex_solv_ions.gro -p ../1.topology/topol.top -pname NA -nname CL -conc 0.150 -neutral # 13 ~ SOL

### minimization ###
cd ../4.minimization

gmx_mpi grompp -f minim.mdp -c ../3.ions/complex_solv_ions.gro -p ../1.topology/topol.top -o em.tpr 
gmx_mpi mdrun -deffnm em


### equilibration ###
cd ../5.equilibriation_first

gmx_mpi grompp -f npt_first.mdp -c ../4.minimization/em.gro -r ../4.minimization/em.gro -p ../1.topology/topol.top -o npt_first.tpr -maxwarn 1
gmx_mpi mdrun -deffnm npt_first

cd ../5.equilibriation_second

gmx_mpi grompp -f npt_second.mdp -c ../5.equilibriation_first/npt_first.gro -r ../5.equilibriation_first/npt_first.gro -t ../5.equilibriation_first/npt_first.cpt -p ../1.topology/topol.top -o npt.tpr -maxwarn 1
gmx_mpi mdrun -deffnm npt


### pul-sim ###

cd ../6.pull

# index creation
gmx_mpi make_ndx -f ../5.equilibriation_second/npt.gro -o ./index.ndx <<EOF
ri 1-160 & a CA
ri 161-200 & ! r SOL & ! r NA & ! r CL
name 17 CAonlyProtein
name 18 onlyPeptide 
q
EOF

gmx_mpi grompp -f pull.mdp -c ../5.equilibriation_second/npt.gro -r ../5.equilibriation_second/npt.gro -p ../1.topology/topol.top -n ./index.ndx -o pull.tpr
gmx_mpi mdrun -deffnm pull -pf pullf.xvg -px pullx.xvg -nb gpu >& ./pull.out
